BCDA-3485 Added better 500 HTTP error response
CMSgov/bcda-app pull request #546
Opened 2020-09-11 14:23 UTC by PatKelsh

### Fixes [BCDA-3485](https://jira.cms.gov/browse/BCDA-3485)

The 500 error response for the job status endpoint was vague and did not provide users with an understanding of what went wrong. This adds a more complete response so users can understand what is happening

### Proposed Changes

* Changed 500 response to include a meaningful response body
### Change Details

### Security Implications

- [ ] new software dependencies

- [ ] security controls or supporting software altered

- [ ] new data stored or transmitted

- [ ] security checklist is completed for this change

- [ ] requires more information or team discussion to evaluate security implications

- [x] no PHI/PII is affected by this change

### Acceptance Validation

### Feedback Requested

2020-09-11 15:05 UTC, mtrang1263 requested changes

2020-09-11 15:05 UTC, mtrang1263 commented on bcda/web/api.go
> -		responseutils.WriteError(&fhirmodels.OperationOutcome{}, w, http.StatusInternalServerError)
Can we add a test to verify we get the expected operational outcome when we encounter a job failure?

2020-09-16 15:22 UTC, mtrang1263 approved these changes

2020-09-16 15:22 UTC, msnook commented
Looks right to me.  Could you merge `master` into your branch so we get a clean run?

2020-09-16 17:00 UTC, merged